command_timeout = 1000

# Add shell indicator to prompt format
format = """$shell$all"""

[shell]
disabled = false
nu_indicator = "[NU](bold green) "
zsh_indicator = ""

[kubernetes]
disabled = false
[terraform]
disabled = true
[java]
disabled = true
[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%T"
